Problem: Integration tests fails because of changes in RPC response (#291)
Solution: Updated test suite to adapt with new response

1) Wallet transaction
       can transfer funds between two wallets:
      AssertionError: expected 'Outgoing' to equal 'outgoing'
      + expected - actual
      -Outgoing
      +outgoing
      
      at expectTransactionShouldBe (test/wallet-transaction.test.ts:324:25)
      at Context.it (test/wallet-transaction.test.ts:102:3)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  2) Wallet transaction
       can transfer funds between two wallets with fee included:
      AssertionError: expected 'Outgoing' to equal 'outgoing'
      + expected - actual
      -Outgoing
      +outgoing
      
      at expectTransactionShouldBe (test/wallet-transaction.test.ts:324:25)
      at Context.<anonymous> (test/wallet-transaction.test.ts:223:3)
      at process._tickCallback (internal/process/next_tick.js:68:7)